<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rooms extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('mdl_rooms');
    } 
    /*
     * Listing of ip_rooms
     */
    function index()
    {
        $data['ip_rooms'] = $this->mdl_rooms->get_all_ip_rooms();
        $this->layout->buffer('content', 'rooms/index',$data);
        $this->layout->render();
    }
    /*
     * Adding a new ip_room
     */
    function add(){   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'active' => $this->input->post('active'),
                'show_on_system' => $this->input->post('show_on_system'),
				'name' => $this->input->post('name'),
            );
            
            $ip_room_id = $this->mdl_rooms->add_ip_room($params);
            redirect('rooms/index');
        }
        else{            
            $this->layout->buffer('content', 'rooms/add');
            $this->layout->render();
        }
    }  
    /*
     * Editing a ip_room
     */
    function edit($id)
    {   
        // check if the ip_room exists before trying to edit it
        $data['ip_room'] = $this->mdl_rooms->get_ip_room($id);
        
        if(isset($data['ip_room']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'active' => $this->input->post('active'),
                    'show_on_system' => $this->input->post('show_on_system'),
					'name' => $this->input->post('name'),
                    'capacity' => $this->input->post('capacity'),
                    'beschreibung' => $this->input->post('beschreibung'),
                    'kategorie' => $this->input->post('kategorie'),
                    'preis1' => $this->input->post('preis1'),
                    'preis2' => $this->input->post('preis2'),
                    'preis3' => $this->input->post('preis3'),
                    
                );

                $this->mdl_rooms->update_ip_room($id,$params);            
                redirect('rooms/index');
            }
            else
            {
                $this->layout->buffer('content', 'rooms/edit',$data);
                $this->layout->render();
            }
        }
        else
            show_error('The room you are trying to edit does not exist.');
    } 
    /*
     * Deleting ip_room
     */
    function remove($id){
        $ip_room = $this->mdl_rooms->get_ip_room($id);
        // check if the ip_room exists before trying to delete it
        if(isset($ip_room['id']))
        {
            $this->mdl_rooms->delete_ip_room($id);
            redirect('rooms/index');
        }
        else
            show_error('The room you are trying to delete does not exist.');
    }

    function get_by_id($id){
         echo json_encode($this->db->query("Select * From ip_rooms where ip_rooms.id=".$id)->row_array());
    }

    function select_free_room($start,$end){
         echo json_encode($this->db->query("Select * From ip_rooms where show_on_system=1 AND ip_rooms.id not in (SELECT item_room FROM ip_invoice_items WHERE item_date_start < '".$end."' AND item_date_end > '".$start."') order by ip_rooms.preis1")->result()); 
    }
    
    function get_companyData(){
         echo json_encode($this->db->query("SELECT user_name,user_company,user_address_1,user_city,user_zip,user_phone,user_email,user_web,user_subscribernumber,user_iban FROM `ip_users` where user_id=1")->row_array());
    }
    
}
